// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfzuhbhnjfqbwmhrmyqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmenVoYmhuamZxYndtaHJteXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2Njk2MTYsImV4cCI6MjA1MDI0NTYxNn0.-04Izzl5icIQkNaUkx8DtmNbXMCSBnZ6Z7SkfjYWUvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);